name:                tui
version:             0.0.0.1
github:              "benjamin-macadam/Haskell-Checkers-Frontend"
license:             MIT

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - brick
  - vty
  - directory
  - cursor
  - microlens-platform

executables:
  tui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - tui
